### ISSUE TITLE
How to train this model with custom data?

### ISSUE THREAD

**Issue by Shuixin-Li** [bluecdm/Long-tailed-recognition#1]
HI, thank you for your wonderful work. I am now want to train this model with my custom data, which are all jpg images now. How can I prepare my data? What kind of structure should I put them in folder? I am kinda new to this field, sorry for the stupid question I asked. 

Thank you in advance!

**Comment by bluecdm** [comment]
Please refer to dataset/imagenet.py and imagenet_inat/data/ImageNet_LT/ImageNet_LT_train.txt.
The first column of ImageNet_LT_train.txt represents the paths to the images and the second column represents corresponding labels.
