### ISSUE TITLE
Fairness of comparison

### ISSUE THREAD

**Issue by qiuzhen8484** [bluecdm/Long-tailed-recognition#4]
Hi, what a great job!! From the released code, I can notice that the teacher model is with greater capacity than student model (resnext101_32x8d vs resnext50_32x4d). Is it fair for comparison?  In my opinion, the model learns from a more powerful teacher. Thanks.

**Comment by bluecdm** [comment]
In sections 4.5 and 4.7 of our paper (https://proceedings.mlr.press/v202/suh23a.html), we found that a powerful teacher does not produce a significant difference. Interestingly, a teacher with lower accuracy can still help students improve, sometimes making students even better than the teacher.
